default: &default
  adapter: mysql2
  host: localhost
  username: nfpmap
  password: nfpmap

test:
  <<: *default
  database: nfpmap_test

development:
  <<: *default
  database: nfpmap

production:
  <<: *default
  database: nfpmap
